version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Build Next.js app...
      - npm run deploy

artifacts:
  files:
    - '**/*'
  base-directory: out
