version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Checking code...
      - npm run check
  build:
    commands:
      - echo Building Next.js app...
      - npm run build
  post_build:
    commands:
      - echo Build finished

artifacts:
  files:
    - '**/*'
  base-directory: '.'
