version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run check
  build:
    commands:
      - npm run build
      - npx next export
artifacts:
  files:
    - '**/*'
  base-directory: out
