version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Checking code...
      - npm run check

  build:
    commands:
      - echo Building Next.js app...
      - npm run build
      - echo Exporting static files...
      - npx next export

artifacts:
  files:
    - '**/*'
  base-directory: out
