import type { Ingredient } from "~/domains/order/types";

export const ingredients: Ingredient[] = [
  { name: "onion", price: 0.25 },
  { name: "potato", price: 0.30 },
  { name: "tomato", price: 0.35 },
  { name: "mushrooms", price: 0.60 },
  { name: "cheese", price: 0.70 },
  { name: "mozzarella", price: 0.85 },
  { name: "cheddar", price: 0.90 },
  { name: "parmesan", price: 1.10 },
  { name: "gorgonzola", price: 1.20 },
  { name: "olives", price: 0.50 },
  { name: "meat", price: 1.50 },
  { name: "beef", price: 1.70 },
  { name: "salami", price: 1.40 },
  { name: "pepperoni", price: 1.45 },
  { name: "bell pepper", price: 0.40 },
  { name: "garlic", price: 0.20 },
  { name: "olive oil", price: 0.30 },
  { name: "white sauce", price: 0.80 },
  { name: "tomato sauce", price: 0.50 },
  { name: "ham", price: 1.30 },
  { name: "pineapple", price: 0.60 },
  { name: "spicy salami", price: 1.50 },
  { name: "jalapeno", price: 0.45 },
  { name: "chili oil", price: 0.25 },
  { name: "truffle oil", price: 2.50 },
  { name: "zucchini", price: 0.45 },
  { name: "eggplant", price: 0.55 },
  { name: "bacon", price: 1.20 },
  { name: "egg sauce", price: 0.80 },
  { name: "shrimp", price: 2.20 },
  { name: "squid", price: 2.00 },
  { name: "garlic butter", price: 0.70 },
  { name: "parsley", price: 0.15 },
  { name: "wild mushrooms", price: 1.80 },
  { name: "cream sauce", price: 0.90 },
  { name: "artichokes", price: 1.00 },
  { name: "salmon", price: 2.80 },
  { name: "dill", price: 0.20 },
  { name: "bbq sauce", price: 0.70 },
  { name: "red onion", price: 0.25 },
  { name: "spinach", price: 0.50 },
  { name: "ricotta", price: 0.85 },
  { name: "sweet corn", price: 0.35 },
];
