
import { PizzaType } from "~/core/types/pizzaType";
import type { Pizza } from "~/domains/pizza/types";

export const pizzas: Pizza[] = [
  {
    name: "Italian",
    type: PizzaType.MEAT,
    price: 8.35,
    sizes: [25, 30, 35],
    ingredients: ["onion", "potato", "tomato", "mushrooms", "cheese", "olives", "meat"],
    rating: 8.5,
    image: "/pizzas/pizza_1.png",
  },
  {
    name: "Venecia",
    type: PizzaType.VEGETARIAN,
    price: 7.35,
    sizes: [25, 30],
    ingredients: ["onion", "potato", "tomato", "mushrooms", "cheese", "olives"],
    rating: 9.3,
    image: "/pizzas/pizza_2.png",
  },
  {
    name: "Meat Lovers",
    type: PizzaType.MEAT,
    price: 9.35,
    sizes: [30, 35],
    ingredients: ["tomato sauce", "onion", "bell pepper", "mozzarella", "beef", "salami"],
    rating: 7.8,
    image: "/pizzas/pizza_3.png",
  },
  {
    name: "Cheese Delight",
    type: PizzaType.VEGETARIAN,
    price: 8.35,
    sizes: [25, 30],
    ingredients: ["mozzarella", "cheddar", "parmesan", "gorgonzola", "tomato"],
    rating: 8.9,
    image: "/pizzas/pizza_4.png",
  },
  {
    name: "Seafood Special",
    type: PizzaType.SEA_PRODUCTS,
    price: 10.95,
    sizes: [30, 35],
    ingredients: ["tomato sauce", "mozzarella", "shrimp", "squid", "garlic", "olive oil"],
    rating: 7.3,
    image: "/pizzas/pizza_5.png",
  },
  {
    name: "Mushroom Magic",
    type: PizzaType.MUSHROOMS,
    price: 8.95,
    sizes: [25, 30],
    ingredients: ["mushrooms", "mozzarella", "white sauce", "onion", "parsley"],
    rating: 6.8,
    image: "/pizzas/pizza_6.png",
  },
  {
    name: "Pepperoni Feast",
    type: PizzaType.MEAT,
    price: 9.75,
    sizes: [30, 35],
    ingredients: ["tomato sauce", "mozzarella", "pepperoni", "oregano"],
    rating: 9.2,
    image: "/pizzas/pizza_7.png",
  },
  {
    name: "Hawaiian",
    type: PizzaType.MEAT,
    price: 9.15,
    sizes: [25, 30],
    ingredients: ["tomato sauce", "mozzarella", "ham", "pineapple", "cheese"],
    rating: 7.1,
    image: "/pizzas/pizza_8.png",
  },
  {
    name: "Diablo",
    type: PizzaType.MEAT,
    price: 9.85,
    sizes: [30, 35],
    ingredients: ["spicy salami", "jalapeno", "mozzarella", "chili oil"],
    rating: 9.1,
    image: "/pizzas/pizza_1.png",
  },
  {
    name: "Truffle Deluxe",
    type: PizzaType.MUSHROOMS,
    price: 10.25,
    sizes: [25, 30],
    ingredients: ["truffle oil", "mushrooms", "mozzarella", "white sauce"],
    rating: 8.7,
    image: "/pizzas/pizza_2.png",
  },
  {
    name: "Capricciosa",
    type: PizzaType.MEAT,
    price: 9.50,
    sizes: [30, 35],
    ingredients: ["ham", "artichokes", "mushrooms", "olives", "tomato sauce"],
    rating: 8.3,
    image: "/pizzas/pizza_3.png",
  },
  {
    name: "Veggie Garden",
    type: PizzaType.VEGETARIAN,
    price: 8.20,
    sizes: [25, 30],
    ingredients: ["zucchini", "eggplant", "onion", "bell pepper", "mozzarella"],
    rating: 7.9,
    image: "/pizzas/pizza_4.png",
  },
  {
    name: "Carbonara",
    type: PizzaType.MEAT,
    price: 9.60,
    sizes: [30, 35],
    ingredients: ["bacon", "egg sauce", "mozzarella", "parmesan"],
    rating: 8.8,
    image: "/pizzas/pizza_5.png",
  },
  {
    name: "Shrimp Lover",
    type: PizzaType.SEA_PRODUCTS,
    price: 11.10,
    sizes: [25, 30],
    ingredients: ["shrimp", "mozzarella", "garlic butter", "parsley"],
    rating: 8.1,
    image: "/pizzas/pizza_6.png",
  },
  {
    name: "Forest Mushroom",
    type: PizzaType.MUSHROOMS,
    price: 8.80,
    sizes: [30, 35],
    ingredients: ["wild mushrooms", "cream sauce", "onion", "cheese"],
    rating: 8.0,
    image: "/pizzas/pizza_7.png",
  },
  {
    name: "Four Seasons",
    type: PizzaType.VEGETARIAN,
    price: 8.90,
    sizes: [25, 30],
    ingredients: ["mozzarella", "tomato", "artichokes", "olives", "mushrooms"],
    rating: 9.0,
    image: "/pizzas/pizza_8.png",
  },
  {
    name: "Salmon Deluxe",
    type: PizzaType.SEA_PRODUCTS,
    price: 11.50,
    sizes: [30, 35],
    ingredients: ["salmon", "mozzarella", "cream", "dill"],
    rating: 9.4,
    image: "/pizzas/pizza_1.png",
  },
  {
    name: "BBQ Chicken",
    type: PizzaType.MEAT,
    price: 9.80,
    sizes: [25, 30],
    ingredients: ["chicken", "bbq sauce", "red onion", "mozzarella"],
    rating: 9.0,
    image: "/pizzas/pizza_2.png",
  },
  {
    name: "Spinach Ricotta",
    type: PizzaType.VEGETARIAN,
    price: 8.60,
    sizes: [25, 30],
    ingredients: ["spinach", "ricotta", "mozzarella", "white sauce"],
    rating: 8.2,
    image: "/pizzas/pizza_3.png",
  },
  {
    name: "Tropical Mix",
    type: PizzaType.MEAT,
    price: 9.10,
    sizes: [30, 35],
    ingredients: ["ham", "pineapple", "sweet corn", "mozzarella"],
    rating: 7.6,
    image: "/pizzas/pizza_4.png",
  },
];
